name: Haskell CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - cabal: "3.12"
            ghc: "9.12.1"
            os: ubuntu-latest
          - cabal: "3.12"
            ghc: "9.10.1"
            os: ubuntu-latest
          - cabal: "3.4"
            ghc: "9.0.2"
            os: ubuntu-latest
          - cabal: "3.2"
            ghc: "8.10.7"
            os: ubuntu-latest
          - cabal: "3.2"
            ghc: "8.8.4"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Cabal Update
        run: |
          cabal v2-update
          cabal v2-freeze $CONFIG
      - uses: actions/cache@v4.2.4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - name: Build all
        run: |
          cabal build all
          cabal sdist all
